---
- hosts: 'all'
  remote_user: 'root'

  vars_prompt:
    - name: "name"
      prompt: "Application name (one-word, can use '_' symbol)"
      default: "example_app"
      private: no
    - name: "domain"
      prompt: "Site domain"
      default: "example.com"
      private: no

  # В данном блоке объявляются переменные, которые будут использоваться в playbook и конфигах, представленных выше
  vars:
    # Пользователь, от лица которого будет происходит деплой
    user: 'deployer'
    # Домашняя директория
    home: '/home/{{ user }}'
    # Директория установки Rbenv
    rbenv_root: '{{ home }}/.rbenv'
    # Путь до нашего приложения
    application: '{{ home }}/apps/{{ name }}'
    secret_key_base: "{{ lookup('password', '/tmp/' + name + '_secret chars=ascii_letters,digits,hexdigits length=128')|lower }}"
    swapfile_location: /swapfile

  # Список задач, которые будут выполнены последовательно
  tasks:
    - name: 'postgresql | check shared folder'
      command: 'test -x {{ application }}/shared'
      register: 'shared_folder_created'
      ignore_errors: yes

    - name: 'postgresql | create shared directory'
      shell: 'mkdir -p {{ application }}/shared/config -m 775 && chown -R {{ user }}:{{ user }} {{ home }}/apps'
      when: 'shared_folder_created|failed'

    - name: 'postgresql | copy database.yml'
      template:
        src: configs/database.yml
        dest: '{{ application }}/shared/config/database.yml'
        owner: '{{ user }}'
        group: '{{ user }}'
        mode: '0644'
      when: 'shared_folder_created|failed'

    - name: 'postgresql | create database'
      shell: 'createdb -U postgres -O postgres -E UTF8 -l en_US.UTF-8 {{ name }}_production'
      when: 'shared_folder_created|failed'

    - name: 'secrets | check'
      command: 'test -f {{ application }}/shared/config/secrets.yml'
      register: 'secrets_yml_copied'
      ignore_errors: yes

    - name: 'secrets | copy secrets.yml'
      template:
        src: configs/secrets.yml
        dest: '{{ application }}/shared/config/secrets.yml'
        owner: '{{ user }}'
        group: '{{ user }}'
        mode: '0644'
      when: 'secrets_yml_copied|failed'

    - name: 'nginx | check config'
      command: 'test -f /etc/nginx/sites-enabled/{{ name }}.conf'
      register: 'nginx_config_copied'
      ignore_errors: yes

    - name: 'nginx | createdir'
      shell: 'rm /etc/nginx/sites-enabled/default; mkdir -p /etc/nginx/sites-enabled/'
      when: 'nginx_config_copied|failed'

    - name: 'nginx | copy config'
      template: 'src=configs/nginx.conf dest=/etc/nginx/sites-enabled/{{ name }}.conf owner=root group=root mode=0644'
      when: 'nginx_config_copied|failed'

    - name: 'nginx | restart service'
      # Модуль service - это ещё одна удобная обёртка, указываем какой сервис и что с ним необходимо сделать
      service: name=nginx state=restarted
      when: 'nginx_config_copied|failed'

    - name: 'puma | check script'
      stat: path=/etc/init/puma.conf
      register: puma_st

    - name: 'puma | copy script if not exists'
      template:
        src: configs/puma.conf
        dest: /etc/init/puma.conf
      when: puma_st.stat.exists == False

    - name: 'puma | check manager script'
      stat: path=/etc/init/puma-manager.conf
      register: puma_manager_st

    - name: 'puma | copy manager script if not exists'
      template:
        src: configs/puma-manager.conf
        dest: /etc/init/puma-manager.conf
      when: not puma_manager_st.stat.exists

    - name: 'puma | check puma apps list'
      stat: path=/etc/puma.conf
      register: puma_apps_st

    - name: 'puma | create puma apps list if not exists'
      file:
        path: /etc/puma.conf
        state: touch
      when: puma_apps_st.stat.exists == False

    - name: 'puma | add app to puma apps list'
      lineinfile:
        dest: /etc/puma.conf
        line: '{{ application }}/current'
        state: present
