---
- hosts: 'all'
  remote_user: 'root'

  vars_prompt:
    - name: "swapfile_size"
      prompt: "Swapfile Size"
      default: "1G"
      private: no

  vars:
    swapfile_location: /swapfile

  tasks:
    - name: Write swapfile
      command: |
        fallocate -l {{ swapfile_size }} {{ swapfile_location }}
      register: write_swapfile
      when: swapfile_size != false

    - name: Set swapfile permissions
      file: path={{ swapfile_location }} mode=600
      when: swapfile_size != false

    - name: Create swapfile
      command: mkswap {{ swapfile_location }}
      register: create_swapfile
      when: swapfile_size != false and write_swapfile.changed

    - name: Enable swapfile
      command: swapon {{ swapfile_location }}
      when: swapfile_size != false and create_swapfile.changed

    - name: Add swapfile to /etc/fstab
      lineinfile: dest=/etc/fstab line="{{ swapfile_location }}   none    swap    sw    0   0" state=present
      when: swapfile_size != false

    - name: Configure vm.swappiness
      sysctl:
        name: vm.swappiness
        value: 10
        state: present
        reload: true

    - name: Configure vm.vfs_cache_pressure
      sysctl:
        name: vm.vfs_cache_pressure
        value: 50
        state: present
        reload: true
